### ISSUE TITLE
在访问页面的时候，找不到 渲染文件下/_nuxt/ 的文件（设置的是master作为根路径）

### ISSUE THREAD

**Issue by feng001-8** [DiscreteTom/dt-blog-boilerplate#47]
报错信息：
GET https://feng001-8.github.io/_nuxt/02bda87.js net::ERR_ABORTED 404 (Not Found)
feng001-8.github.io/:4     GET https://feng001-8.github.io/_nuxt/865e8e6.js net::ERR_ABORTED 404 (Not Found)
feng001-8.github.io/:4     GET https://feng001-8.github.io/_nuxt/998a0d0.js net::ERR_ABORTED 404 (Not Found)
feng001-8.github.io/:4     GET https://feng001-8.github.io/_nuxt/f698162.js net::ERR_ABORTED 404 (Not Found)
favicon.ico:1     GET https://feng001-8.github.io/favicon.ico 404 (Not Found)
manifest.29bb801c.json:1     GET https://feng001-8.github.io/_nuxt/manifest.29bb801c.json 404 (Not Found)
manifest.29bb801c.json:1 Manifest: Line: 1, column: 1, Syntax error.

访问路径：
《 link rel="preload" href="/_nuxt/02bda87.js" as="script"
     link rel="preload" href="/_nuxt/f698162.js" as="script"
     link rel="preload" href="/_nuxt/865e8e6.js" as="script"
     link rel="preload" href="/_nuxt/998a0d0.js" as="script" 》

文件信息：
https://github.com/feng001-8/feng.github.io/tree/master/_nuxt

  请问这个该怎么做

**Comment by DiscreteTom** [comment]
简单来说：您应该创建一个名为`feng001-8.github.io`的repository，而不是现在的`feng.github.io`

参考此文：https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages

> To publish a user site, you must create a repository owned by your personal account that's named `<username>.github.io`.

然后就可以通过 https://feng001-8.github.io 访问

由于目前您的repository名称和用户名不一致，可以通过如下路径实现访问：https://feng001-8.github.io/feng.github.io/ 当然因为path里面有额外的内容，很多文件都会404

================

另外，此博客模板已年久失修，可以考虑使用 https://vitepress.dev/ 之类的更加现代的方案

**Comment by feng001-8** [comment]
非常感谢 ！豁然开朗！
感谢你的建议我觉得这个足够简洁目前比较合适我，如果后面有需要的话我想我会换一个模版 。
