### ISSUE TITLE
出现多余“0”文件和找不到自己的md文件

### ISSUE THREAD

**Issue by feng001-8** [DiscreteTom/dt-blog-boilerplate#48]
### 问题一（“0”文件）：
**在 `yarn generate` 后总是会出现一个0的目录和文件，我很确信自己没有设置关于0的任何信息，我多次在dist目录尝试删除0文件，后启动`yarn start` 没有效果总是会出现** 
<img width="1069" alt="Screenshot 2023-12-03 at 15 42 18" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/ed0128fd-2bdf-4ded-9a52-5f1aab89377a">

### 问题二（md文件）：

<img width="1260" alt="Screenshot 2023-12-03 at 15 50 53" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/8a8b2e83-1e49-4eab-83da-ee9e2cda5e31">

<img width="1352" alt="Screenshot 2023-12-03 at 15 37 57" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/7e9e6629-035b-4807-b07a-fbbbaf622b6d">

#### 路径：

<img width="374" alt="Screenshot 2023-12-03 at 15 58 26" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/871bb8b4-1116-43f7-a8e9-a96f16ca4d4a">

文件的`_config.yml`:

<img width="867" alt="Screenshot 2023-12-03 at 15 58 55" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/6a59a7a9-6c97-4842-8bee-eb33a56eabd1">

#### 文件的配置：

<img width="876" alt="Screenshot 2023-12-03 at 15 59 31" src="https://github.com/DiscreteTom/dt-blog-boilerplate/assets/114282544/9e26171b-5589-4369-97d9-98e1e6b9eb80">

**Comment by feng001-8** [comment]
对占用您宝贵的时间我深表歉意！

**Comment by DiscreteTom** [comment]
## 问题1

请尝试删除文件夹中的所有`.DS_Store`文件。

目前来看：只有`content`和文件夹和`4@Information_Security`文件夹中有这个文件，恰好生成的站点里面也有一个top-level的`0`和https://feng001-8.github.io/Information_Security/ 文件夹下的`0`。大概率是这个导致的。

此博客模板会扫描`content`文件夹下的所有文件，并为所有不是以`_`开头的文件建立一个入口。所以`.DS_Store`会被视为没有文件名、编号为0、后缀为`DS_Store`的文件。

## 问题2

建议尝试使用英文文件名

目前来看英文文件名的都可以正常访问，比如 https://feng001-8.github.io/posts/text/

如果希望页面里面显示的标题为中文，可以设置`title`属性

**Comment by feng001-8** [comment]
确实是这样！困扰我两天的Blog终于解决了，这也是我第一次在github问问题，让我感到惊喜，我知道对于有些问题很“幼稚”，在此请接收我的诚挚的谢意！☺️
